### ISSUE TITLE
Response content size can be zero

### ISSUE THREAD

**Issue by MMquant** [gwen001/cloudflare-origin-ip#10]
```
[+] Reading datas from file: ips
[+] 0 subdomains found, 27 ips added
[+] 27 unique ips collected
[+] Performing reference request...
Status=404, Length=0, Headers=9, Content-Type=text/plain; charset=utf-8
[+] Testing bypass...
[-] 40.126.38.21: Exceeded 30 redirects.
Traceback (most recent call last):
  File "/app/cloudflare-origin-ip.py", line 584, in <module>
    pool.map( partial(testBypass3,t_multiproc,r_reference,host), t_ips )
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/app/cloudflare-origin-ip.py", line 458, in testBypass3
    score = responseCompare( r_reference, r )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/cloudflare-origin-ip.py", line 490, in responseCompare
    score['dist_content'] = 100 - ( dist*100 / len(r_reference.content[0:COMPARE_FIRST_CHARS]) )
                                    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by MMquant** [comment]
```
if len(r_reference.content[0:COMPARE_FIRST_CHARS]) != 0:
    score['dist_content'] = 100 - ( dist*100 / len(r_reference.content[0:COMPARE_FIRST_CHARS]) )
```

seems to fix it

**Comment by gwen001** [comment]
Should be ok now, let me know.

Thank you!

**Comment by MMquant** [comment]
This is fixed but in the meantime I found another division by zero bug. Will create a new issue.
