### ISSUE TITLE
Facing error while running the tool

### ISSUE THREAD

**Issue by Shuvamoy** [gwen001/cloudflare-origin-ip#13]
python3 cloudflare-origin-ip.py 
Traceback (most recent call last):
  File "/home/kali/Downloads/tools/cloudflare-origin-ip/cloudflare-origin-ip.py", line 6, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/home/kali/.local/lib/python3.11/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by gwen001** [comment]
Can't reproduce the bug sorry, tested with python 3.9/3.10/3.11, it works for me.
Try to update your install.
