### ISSUE TITLE
NameError: name 'ip' is not defined

### ISSUE THREAD

**Issue by pguardiario** [gwen001/cloudflare-origin-ip#14]
Can someone suggest a fix for this?

Traceback (most recent call last):
  File "cloudflare-origin-ip.py", line 559, in <module>
    grabber_securitytrails( domain )
  File "cloudflare-origin-ip.py", line 275, in grabber_securitytrails
    if not ip in t_ips:
NameError: name 'ip' is not defined

**Comment by ww7** [comment]
Same on Python 3.8

**Comment by CloseC4ll** [comment]
same

**Comment by xiaoyongwu** [comment]
I have the simple fix [here: https://github.com/gwen001/cloudflare-origin-ip/pull/16](https://github.com/gwen001/cloudflare-origin-ip/pull/16)

**Comment by n3wpr** [comment]
Or you can just edit your own file `cloudflare-origin-ip.py` on line 275. Change the content `if not ip in t_ips:` for this one `if not value['ip'] in t_ips:`.
